### ISSUE TITLE
Beispiele im ui funktionieren nicht

### ISSUE THREAD

**Issue by Hypnos3** [Sineos/node-red-contrib-weatherman#1]
![image](https://user-images.githubusercontent.com/12692680/44947593-6b230600-ae0f-11e8-8535-e3fee4387f77.png)

Wohin müssen die Dateien von Steelseries Gauges denn hinkopiert werden, damit die Anzeige im Ui funtioniert?

**Comment by Sineos** [comment]
Sorry, bin noch nicht dazu gekommen, ein kleines Tutorial zu schreiben. Für die zusätzlichen Skript Bibliotheken brauchst du ein `httpStatic` Verzeichnis für NR. Ich hab meines unter `/usr/local/sdcard/www/addons/red/static/` angelegt.
Dazu dann noch die `httpStatic` Einstellung in `/usr/local/addons/redmatic/etc/sttings.json`

```
{
	"uiPort": 1880,
	"uiHost": "127.0.0.1",
	"flowFile": "flows.json",
	"userDir": "/usr/local/addons/redmatic/var",
	"httpRoot": "/addons/red",
	"httpStatic": "/usr/local/sdcard/www",
	"logging": {
		"ain": {
			"level": "info",
			"metrics": false,
			"audit": false
		}
	}
} 
```

Damit sind zusätzlich Dateien, wie Bilder, Skripte usw. unter `http://<ccu-adresse>/addons/red/static/...` erreichbar.

Die einzelnen Bibliotheken liegen dann in einem `scripts` Ordner:

```
<script type="text/javascript" src="/addons/red/static/scripts/steelseries-min.js"></script>
<script type="text/javascript" src="/addons/red/static/scripts/tween-min.js"></script>
<script type="text/javascript" src="/addons/red/static/scripts/RGraph.common.core.js"></script>
<script type="text/javascript" src="/addons/red/static/scripts/RGraph.radar.js"></script>
```

Mit dem Update, dass ich gerade hoch geschoben haben sind noch RGraph Libs dazugekommen: https://www.rgraph.net/

**Comment by Hypnos3** [comment]
Ok, Besten Dank.

**Comment by Sineos** [comment]
Hier jetzt ein bisschen ausführlicher: https://github.com/Sineos/node-red-contrib-weatherman/blob/master/README_DE.md
